version: "3"
services:
  nginx:
    container_name: nginx_reverse_proxy
    build: ./nginx_reverse_proxy
    ports:
      - 443:443
    depends_on:
      - express_app
  express_app:
    container_name: express_app
    build: .
    ports:
      - 3000:3000
